### ISSUE TITLE
[Feature] Add option to download with server timestamp

### ISSUE THREAD

**Issue by ZorinFoss** [amir1376/ab-download-manager#1]
Hi @amir1376 

First of all i want to thank you for your efforts to develop this beautiful app.

Please add option to download with server timestamp. This option exist in aria and it will be good to add it to `ABDownloadManager`

![Screenshot_20240327_124142](https://github.com/user-attachments/assets/b495f9fa-08cc-4251-9015-81b0562ea6c3)

Thanks,

**Comment by amir1376** [comment]
@ZorinFoss
Hello Thanks for suggesting this feature It could  be useful, I will consider it next updates

**Comment by ZorinFoss** [comment]
Thank you ❤️
