### ISSUE TITLE
[Feature]  Change Font Size

### ISSUE THREAD

**Issue by rbvk** [amir1376/ab-download-manager#10]
I'm using a 2k screen and the font size is really small to read.

pd: thanks for your work, incredible pice of software

**Comment by amir1376** [comment]
I'm glad to hear that,Thanks 🙏
I will consider this enhancement

In the source code I already have this feature but I disabled this at the moment 
because there is some issues in UI framework that I am using, so I have to find a workaround for that

**Comment by amir1376** [comment]
as I mentioned earlier.

> there is some issues in UI framework that I am using, so I have to find a workaround for that

you can vote for this issue in their issue tracker [here](https://youtrack.jetbrains.com/issue/CMP-6857/Compose-Desktop-ignores-LocalDensity-for-window-sizes)

**Comment by amir1376** [comment]
Fixed now.
