### ISSUE TITLE
[Feature] Ability to set "Use Catagory" off by default

### ISSUE THREAD

**Issue by btyrellb125** [amir1376/ab-download-manager#122]
I do not personally want my downloads in folders based on categories, so I have to keep uncecking the box, but if you download a lot of things at once it gets annoying.

**Comment by amir1376** [comment]
@btyrellb125 Hi. I understand.
- I can add a feature to automatically check/uncheck `Use category` based on the last time you check/uncheck it.
- but if you uncheck the `Use category` that item will not categorized. (you can't filter items based on their categories in the list)
- if you want to have both categories and also not use separate folders for each category you can change all category folders to the default download folder
- I may add an option to categories to allow them save files in the default download location instead

**Comment by amir1376** [comment]
@btyrellb125 right click on the category and press `Edit Category`

**Comment by btyrellb125** [comment]
ah thanks, ill do that for now then

**Comment by Plexprofile** [comment]
> * I can add a feature to automatically check/uncheck `Use category` based on the last time you check/uncheck it.
> 
> * but if you u

It seems the`Use category` can not be turned completely off yet in the latest 1.3 build, s is feature going to be added in the next release?

**Comment by amir1376** [comment]
In the next release you can uncheck all category download location (they are optional now)

**Comment by RashiqAzhan** [comment]
I've unchecked this tick box, but it still keeps categorizing the download.

![image](https://github.com/user-attachments/assets/3caddaf9-bb0f-4ac2-8801-f75869836e79)

Am I missing some steps?

![image](https://github.com/user-attachments/assets/ae38ac4a-868c-48fd-b881-0cd415bf650b)
