### ISSUE TITLE
Suggestion: Provide multilingual support.

### ISSUE THREAD

**Issue by tarimren-admin** [amir1376/ab-download-manager#128]
Suggestion: Provide multilingual support.

**Comment by amir1376** [comment]
@tarimren-admin Hi dear. I am working on it. it has some issues I will publish it as soon as I can

**Comment by NB-Group** [comment]
Hello, @amir1376 

I recently came across your amazing multithreaded downloader project, and I appreciate the hard work that has gone into it. As a native Chinese speaker, I noticed that the project lacks Chinese localization, which could greatly enhance the usability for Chinese users.

I would like to contribute by adding Chinese language support. This would involve translating the user interface and any relevant documentation into Chinese. If you're open to this idea, I can start working on it right away and submit a pull request with the changes.

Please let me know if you would be interested in this contribution, or if you have any guidelines for localization that I should follow.

Thank you for considering this request!

**Comment by mzky** [comment]
The following platforms are available for multilingual support
https://hosted.weblate.org
https://app.transifex.com

**Comment by amir1376** [comment]
@NB-Group Hi dear. thank you for you interest in contribution to this project.
I am now implementing localization support in the app. 
And of course you can help me with the translation of your native language after I implemented that

**Comment by NB-Group** [comment]
Hi,
Thank you for your quick response! I’m glad to hear that you are implementing localization support in the app. I would be happy to help with the translation once it’s ready. Please let me know how I can assist you further, and I look forward to contributing to the project.
