### ISSUE TITLE
Chocolatey package

### ISSUE THREAD

**Issue by amir1376** [amir1376/ab-download-manager#129]

**Comment by amir1376** [comment]
Hi dear @Aurocosh I just wanted to [inform you](https://github.com/amir1376/ab-download-manager/issues/13#issuecomment-2351598665) about the change that I made to the installer

It now uses `Nsis` installer in Windows

**Comment by Aurocosh** [comment]
Hello. I have updated the chocolatey installation script from Msi to Nsis. Installation of versions 1.2 and above will work correctly now.

**Comment by amir1376** [comment]
@Aurocosh Thanks a lot.
