### ISSUE TITLE
Scoop package

### ISSUE THREAD

**Issue by trymeouteh** [amir1376/ab-download-manager#13]
Please release this as a scoop package

**Comment by amir1376** [comment]
@trymeouteh
Thanks for your suggestion🙏,I am busy with stabling app features
after that, I will come back and improve installer and installation methods

**Comment by dtantono** [comment]
HI OP
You can track the progress here
https://github.com/ScoopInstaller/Extras/issues/13835

**Comment by sitiom** [comment]
- Resolved in https://github.com/ScoopInstaller/Extras/pull/13839

![image](https://github.com/user-attachments/assets/6bace403-de86-48bf-a835-d543914be3d9)

**Comment by sitiom** [comment]
@amir1376 Can you close this issue now? Issue has been resolved

**Comment by amir1376** [comment]
@sitiom Thank you very much for your work❤️
I updated the `README.md` and add the `scoop` package manager in the [installation](https://github.com/amir1376/ab-download-manager#installation) section

**Comment by dnet890** [comment]
@amir1376 if you want [chocolatey](https://github.com/chocolatey-community/chocolatey-package-requests/issues/1535). it is on progress as well.

**Comment by amir1376** [comment]
@sitiom is it works with the zip portable file? or with the `msi` package?
I want to change msi package installer and switch to `inno setup` or `nsis` maybe, because of #47 which is buggy and not ideal!

**Comment by sitiom** [comment]
If you check the [manifest](https://github.com/ScoopInstaller/Extras/blob/master/bucket/abdownloadmanager.json), it uses the portable zip file. To note, Scoop installs portable versions of apps (with the exception of the [Nonportable](https://github.com/ScoopInstaller/Nonportable) bucket).

**Comment by amir1376** [comment]
@sitiom I mean the [chocolatey](https://github.com/chocolatey-community/chocolatey-package-requests/issues/1535) that you mentioned above

**Comment by sitiom** [comment]
> @sitiom I mean the [chocolatey](https://github.com/chocolatey-community/chocolatey-package-requests/issues/1535) that you mentioned above

I did not mention the chocolatey package 😅, but it uses both (one package for each): https://github.com/chocolatey-community/chocolatey-package-requests/issues/1535#issuecomment-2306832658

**Comment by amir1376** [comment]
@sitiom Sorry my bad.😅. I wanted to mention dear @dnet890

**Comment by dnet890** [comment]
it is under pending review and it is not visible on chocolatey internal search engine. But, the users can input the command directly and it works properly. However, if you want a big change, especially on package format. you should notify them via Github for proper adjustment.

**Comment by Aurocosh** [comment]
I am the maintainer of the chocolatey package. The package passed moderation and is now available.

If you want to change the installer from msi to Inno or NSIS then feel free to do so. Both Inno Setup and NSIS are compatible with chocolatey. Just contact me when the installer format changes and i will update the package accordingly.

**Comment by amir1376** [comment]
@Aurocosh Thanks man. sure

**Comment by sharpchen** [comment]
can't find package on scoop
![image](https://github.com/user-attachments/assets/663bd48a-cefa-4f51-bcd0-7f7adfe042bc)

**Comment by amir1376** [comment]
I changed the format of the release filename. to "$APPNAME_$VERSION_$PLATFORM_$ARCH.$EXT

does it require modifications to the scoop's extra bucket repository?

**Comment by sitiom** [comment]
Yes, thanks for informing me:
- https://github.com/ScoopInstaller/Extras/pull/14453

Are you planning to release binaries for other architectures?

**Comment by amir1376** [comment]
Not at the moment, but since I plan to add a auto-update feature to the app, and new architectures might be added in the future, I decided to do this from the start to avoid any conflicts later.
