### ISSUE TITLE
Add Persian Language

### ISSUE THREAD

**Issue by R9TRH** [amir1376/ab-download-manager#132]
Hi my friend! as you and me are living in Iran, I love to see our native language in your app :) I'll be happy to see Farsi language in next versions. After all, Your project is so great and perfect. I have currently 0 issues in v1.3.0

**Comment by amir1376** [comment]
@R9TRH Hi dear and thank you.🙏 
Of course I want that too. 
I implemented the localization and it almost ready to be published but there is a problem please track this issue #128 as I will update there.

**Comment by R9TRH** [comment]
Thanks 🙏
