### ISSUE TITLE
Are there any plans to support other download protocols

### ISSUE THREAD

**Issue by taotaoyouyou** [amir1376/ab-download-manager#159]
such as:P2P,BitTorrent,torrent,ed2k,thunder

**Comment by realgooseman** [comment]
I think this would bloat the download manager and make it heavier on usage. If additional download protocols should be supported in the future, they should come in plugins so each user can choose which one to enable or disable.

This topic has already been discussed in the Telegram group, go take a look there for more information.

**Comment by amir1376** [comment]
> such as:P2P,BitTorrent,torrent,ed2k,thunder

Hi @taotaoyouyou for now I don't have plan to add these protocols. (maybe later but not now)
