### ISSUE TITLE
Feature Request : Auto close download window after download complete. 

### ISSUE THREAD

**Issue by codextent2019** [amir1376/ab-download-manager#161]
Hello,
I would like to suggest a new feature for the project that would **automatically close the download window once the download is complete**. This would provide a more seamless user experience and reduce the need for manual intervention.

Currently, when a user initiates a download, they have to manually close the download window once the process is finished. This can be inconvenient, especially if the user forgets to close the window or if they have multiple downloads running simultaneously.

I believe this feature would be a valuable addition to the project and would greatly enhance the overall user experience. I'm happy to provide any additional details or feedback as needed.

Thank you for considering this feature request.

**Comment by amir1376** [comment]
it is now optional you can disable it in the settings in the next release
