### ISSUE TITLE
Bug : open folder not working

### ISSUE THREAD

**Issue by Mahantor** [amir1376/ab-download-manager#164]
The option to open the folder after the download is complete does not work
I am using the latest portable version
![Screenshot 2024-11-01 225717](https://github.com/user-attachments/assets/1d8acf8e-a2a1-45da-bc16-f5bb78b69376)

**Comment by amir1376** [comment]
Hi. what version you are using in what platform?

**Comment by Mahantor** [comment]
> Hi. what version you are using in what platform?

1.4.1 portable

**Comment by amir1376** [comment]
This is not 1.4.1 nor 1.4.0. because. please check that version. because I changed the "Folder" to "Open Folder" and "File" to "Open File" since 1.4.0 !
I think you have two versions in your system. you can see the running version by going to `Help` > `About` 

the problem with open folder in linux was fixed a few versions ago

**Comment by Mahantor** [comment]
yes is 1.4.1
I had this problem for several days
I checked today and it is working properly

**Comment by Mahantor** [comment]
https://github.com/user-attachments/assets/17e1e4f9-bb4d-4803-9de7-6868853771a9

**Comment by amir1376** [comment]
That's weird!
I am using this command to open the downloaded file folder
```bash
cmd /c explorer.exe /select, <file-path>
```
the <file-path> is an absolute path of the downloaded file for example `C:/users/Downloasds/ABDM/Compressed/archive.rar`

You can test it manually in your terminal (cmd)

if it doesn't work try this instead. let see if it prints some errors in the terminal?

```bash
explorer.exe /select, <file-path>
```

I think there is a problem with these commands in your system.

**Comment by Mahantor** [comment]
I understood why it happens
The problem was that C:\Windows and C:\Windows\System32 were not defined for the path variable in Environment Variables.
In my opinion, to avoid this problem, it is better to replace the command cmd /c explorer.exe /select, <file-path> with the this command 
`C:\Windows\explorer.exe /select,`
 in this case even if the paths are not defined correctly, select file will be done correctly

**Comment by amir1376** [comment]
Did you manually remove those in PATH ?

**Comment by Mahantor** [comment]
no

**Comment by amir1376** [comment]
I saw that almost all programs act like this (depend on PATH for accessing `cmd` and `explorer`). this is weird that these directories are not set for you!

BTW thanks for mentioning that.

**Comment by amir1376** [comment]
it will use the native windows API for opening folders in the next version
