### ISSUE TITLE
Feature request : add download completed option

### ISSUE THREAD

**Issue by Mahantor** [amir1376/ab-download-manager#165]
Please add the option to remove completed downloads to the toolbar like IDM
![Screenshot 2024-11-04 105022](https://github.com/user-attachments/assets/df1c0211-966f-4c61-81c4-c706c59ac520)

**Comment by amir1376** [comment]
@Mahantor Hi there. this feature already exists! Go to `Tasks` > `Delete` > `All Finished`

**Comment by Mahantor** [comment]
please add this option to toolbar

**Comment by amir1376** [comment]
> please add this option to toolbar

this is not a common feature to be added in the toolbar.
