### ISSUE TITLE
Bug : Failure to display the download window after resume

### ISSUE THREAD

**Issue by Mahantor** [amir1376/ab-download-manager#167]
After resuming the download from within the software
![Screenshot 2024-11-05 090456](https://github.com/user-attachments/assets/4f75611c-636d-4e35-9ba4-1f7d285b6c01)

the download window is not displayed

By the download window, I mean this window

![Screenshot 2024-11-05 090431](https://github.com/user-attachments/assets/34a2d4e9-1148-423a-b0bc-d9dc8080cdea)

**Comment by amir1376** [comment]
@Mahantor I dear it is not a bug but an enhancement. it could be added as an option.

**Comment by amir1376** [comment]
Done.
