### ISSUE TITLE
[Feature] Create Custom Category

### ISSUE THREAD

**Issue by BoscoFZ** [amir1376/ab-download-manager#17]
Could you please support adding a feature to create a custom category and automatically put the following file types into this category, similar to how it's done in IDM or FileCentipede? For example, I want to create a custom category named "MyCustomVideos" with a path of G:\LUV, and file types such as *.mp3, *.wav, *.wma, *.mpa, *.ram, *.ra, *.aac, *.aif, *.m4a, *.tsa, *.flac, *.aiff. Thank you very much!

Below is an example image of the feature I’m referring to.

<img src="https://i.imgur.com/qqyMwDv.png"> <img src="https://i.imgur.com/iD0HAYg.png">

<img src="https://i.imgur.com/1LZ3bRb.png"> <img src="https://i.imgur.com/BG44WoK.png">

**Comment by amir1376** [comment]
Good idea, Thanks for your suggestion

**Comment by amir1376** [comment]
Done.
