### ISSUE TITLE
UI in Wayland Is Very Small

### ISSUE THREAD

**Issue by teruis** [amir1376/ab-download-manager#171]
Hello!
Everything is working well, but the UI in Wayland is very small for me. Can you fix that?

Operation:
    - Ubuntu 24.04 Wayland

![Screenshot from 2024-11-07 13-06-54](https://github.com/user-attachments/assets/a598f971-1833-481a-919d-5e0009aa4cbf)

**Comment by YALdysse** [comment]
Same issue, but on X11.

**Comment by Mahantor** [comment]
same issue in windows

**Comment by asdefasdf** [comment]
I totally agree, the interface is very small.

**Comment by amir1376** [comment]
Hi. its not related to X11 or Wayland. it needs implementing a UI Scaling feature

**Comment by YALdysse** [comment]
@amir1376, please, add font scale option as soon as you can. It is too hard to use application on Manjaro with FullHD screen.

**Comment by YALdysse** [comment]
@amir1376, This issue can be closed as completed.

**Comment by amir1376** [comment]
did UI Scale fix the problem ?
