### ISSUE TITLE
The interface size needs to be increased.

### ISSUE THREAD

**Issue by asdefasdf** [amir1376/ab-download-manager#177]
Please increase the interface size and the font is very small.
Everything in the interface is very small.

**Comment by asdefasdf** [comment]
Windows 10

**Comment by asdefasdf** [comment]
![Uploading IMG_20241110_231916_648.jpg…]()

**Comment by asdefasdf** [comment]
![IMG_20241110_231916_648](https://github.com/user-attachments/assets/854c9266-2703-4aba-a503-468693e0b688)

**Comment by asdefasdf** [comment]
Very small program interface.

**Comment by YALdysse** [comment]
@amir1376, This issue can be closed as completed.
