### ISSUE TITLE
Scaling issue in fedora Linux.

### ISSUE THREAD

**Issue by DestroyerV** [amir1376/ab-download-manager#184]
When I have installed application all things were good but after few days the UI of the application became very small automatically.

OS: Fedora 41
Default Scaling: 125%
Application Version: 1.4.2

![image](https://github.com/user-attachments/assets/bf318dba-542e-46df-a897-97d7a88966ea)

**Comment by YALdysse** [comment]
@amir1376, This issue can be closed as completed.
