### ISSUE TITLE
Remember last used save location

### ISSUE THREAD

**Issue by DRYN07** [amir1376/ab-download-manager#185]
It would be great if it could remember the last download location, so it wouldn’t need to be specified every time. Unfortunately, the default location isn't very useful if someone typically downloads things in an organized manner :)

**Comment by amir1376** [comment]
Hi there. last saved location is available as you can see here

![image](https://github.com/user-attachments/assets/d9dd421d-53cb-4ba7-ade5-fcdd30902c13)

BTW you can change `Category Download Location` too!

![image](https://github.com/user-attachments/assets/ba39fb9b-fd00-4e26-9334-766a60d50ed4)

**Comment by candrapersada** [comment]
how to use Remember last used save location without enable Category?
