### ISSUE TITLE
(Question) Confusing wodings

### ISSUE THREAD

**Issue by alex3236** [amir1376/ab-download-manager#199]
![image](https://github.com/user-attachments/assets/ae2fdd49-a556-47dd-95a8-c38fdbccbe6c)

The description of this option made me think that the maximum value for this is 5 when I first saw it.

Changing it to something like "Thread count a download can have up to" will be better, since the value of the current setting is already given on the right, there is no need to state it in the description.

**Comment by amir1376** [comment]
Hi. it describes about the current selected value
if you want to see more details about each setting press on `?` after the title. which gives you a description for that.

This is a design decision that I made for now. but I welcome design improvements (UI/UX)
