### ISSUE TITLE
Issue in deleting the .abdm directory

### ISSUE THREAD

**Issue by AliMehraji** [amir1376/ab-download-manager#205]
There is an issue in running the `delete_app_config_dir` via calling the URL :

https://github.com/amir1376/ab-download-manager/blob/master/README.md#Uninstall

I couldn't figure it out 
I'll fix it

**Comment by amir1376** [comment]
it also does not show prompt before deleting it.

**Comment by AliMehraji** [comment]
When you run a script via curl and pipe it directly to bash, it is executed in a non-interactive mode. This means that any script commands requiring user interaction (such as read -p) will not work as expected. The script won't pause for user input, so the delete_app_config_dir function won't behave correctly because it relies on user input.

what is your recommendation? 
remove the user interaction part or 
comment it out in Readme to download the script and run it locally


chatGPT recommendation script is like the below: 

```bash
delete_app_config_dir() {
    local force_delete="${1:-false}"

    if [[ "$force_delete" == "true" ]]; then
        rm -rf "$HOME/.abdm"
        logger "$APP_NAME settings and download lists directory: $HOME/.abdm removed."
    else
        local answer
        read -p "Do you want to continue? [Y/n]: " -r answer
        answer=${answer:-Y}  # Set default to 'Y' if no input is given

        case $answer in
            [Yy]* )
                rm -rf "$HOME/.abdm"
                logger "$APP_NAME settings and download lists directory: $HOME/.abdm removed."
                ;;
            [Nn]* )
                logger "Remove The $HOME/.abdm directory manually."
                ;;
            * )
                logger error "Please answer yes or no."
                delete_app_config_dir
                ;;
        esac
    fi
}
```

**Comment by amir1376** [comment]
We can also use this

```bash
bash <(curl -fsSL https://raw.githubusercontent.com/amir1376/ab-download-manager/master/scripts/uninstall.sh)
```
![image](https://github.com/user-attachments/assets/68f0a716-9889-49b6-a076-5f230eab1be7)

**Comment by amir1376** [comment]
I noticed that if the app was not running when user ran the uninstall script, the script will finished after the execution of `pkill` command
(because it's return code is not `0` the script exits immediately.)

It also happens on other commands that this script has (`rm`, `unlink`, etc..).  which is not good! maybe some of these files are missing. the script should not finished in these situations

**Comment by amir1376** [comment]
@AliMehraji I noticed that, If the application was not running when user execute the uninstall script, the script will be exited after the execution of `pkill` command
(because it's return code is not `0` the script exits immediately.)

It also happens on other commands that this script has (`rm`, `unlink` etc..).  which is not good! maybe some of these files are removed by user (which is acceptable). the script should not be exited in those steps

**Comment by AliMehraji** [comment]
> @AliMehraji Hello again and sorry for the late.
> 
> We can also use this.
> 
> ```shell
> bash <(curl -fsSL https://raw.githubusercontent.com/amir1376/ab-download-manager/master/scripts/uninstall.sh)
> ```
> 
> is it OK?
> 
> ![image](https://private-user-images.githubusercontent.com/38394888/393056512-68f0a716-9889-49b6-a076-5f230eab1be7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1MTI1NzcsIm5iZiI6MTczMzUxMjI3NywicGF0aCI6Ii8zODM5NDg4OC8zOTMwNTY1MTItNjhmMGE3MTYtOTg4OS00OWI2LWEwNzYtNWYyMzBlYWIxYmU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDE5MTExN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmZDNjNDQ5YmJjODExZTNjZTIwODAyMzVlMzNmNzM4MjFiNzI2YjRlMGY4ZDY3Njk1YWY1ZDViMjAzMTA0NDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NSucgbRZI34wLuKC5iIyPQZBNpYUr8HpT0PTZcANKTE)

Yeap , LGTM

**Comment by amir1376** [comment]
> for rm and unlink, we can use find first , if it found then delete
is it good ?

yes I agree.

**Comment by AliMehraji** [comment]
> > for rm and unlink, we can use find first , if it found then delete
> > is it good ?
> 
> yes I agree.

if All is good in [PR #285 ](https://github.com/amir1376/ab-download-manager/pull/285), 
we close this issue

**Comment by amir1376** [comment]
Yes. I tested it. and it works. thanks for the PR

**Comment by amir1376** [comment]
> > > for rm and unlink, we can use find first , if it found then delete
> > > is it good ?
> > 
> > 
> > yes I agree.
> 
> if All is good in [PR #285 ](https://github.com/amir1376/ab-download-manager/pull/285), we close this issue

Yes. I tested it. and it works. thanks for the PR
