### ISSUE TITLE
[Feature Request] Download video website like youtube...

### ISSUE THREAD

**Issue by thohnb** [amir1376/ab-download-manager#21]
Hello !
It so great that finally we can have open source download manager. 
I love it .
Just one thing, could you made feature that allow to download video from **youtube** , dailymotion... . I think is related with AB Download manager extension on firefox/chrome.

Thanks you for your application.

**Comment by amir1376** [comment]
@thohnb Thank you for your suggestion
the same issue is already exists at https://github.com/amir1376/ab-download-manager/issues/9
please follow that issue instead

I close this as  duplicate
