### ISSUE TITLE
[Bug] Settings didn't save properly

### ISSUE THREAD

**Issue by FiorenMas** [amir1376/ab-download-manager#22]
Settings are not saved after completely exiting the application and restarting it.
"Dymatic part creation" can't save. Other settings might require multiple restarts (2-3 times) to be saved.

===
ab-download-manager v1.0.6
Window 10 21H2 x64

**Comment by amir1376** [comment]
@FiorenMas Thank you. I fixed `dynamic part creation` setting not saved on app exit

But
> Other settings might require multiple restarts (2-3 times) to be saved.

I don't face that problem can you tell me how can I reproduce this ?

**Comment by FiorenMas** [comment]
Thank you for fixing the bug. The issue with other settings not saving is infrequent, and I haven't been able to consistently reproduce it. I will monitor this issue and report back with more details if it happens again.
