### ISSUE TITLE
Add change category in Settings

### ISSUE THREAD

**Issue by andymachs** [amir1376/ab-download-manager#240]
Please add change category in Settings.

**Comment by amir1376** [comment]
Hi there. you can change category settings by right clicking on its name and press `Edit Category`

**Comment by andymachs** [comment]
> Hi there. you already can change category settings by right clicking on its name and press `Edit Category`

How to change category? I do not know according to your description.

**Comment by amir1376** [comment]
> > Hi there. you already can change category settings by right clicking on its name and press `Edit Category`
> 
> How to change category? I do not know according to your description.

![image](https://github.com/user-attachments/assets/35834a31-5a6d-4d41-af0b-ad646805d228)

**Comment by andymachs** [comment]
I see, Thank you!

**Comment by amir1376** [comment]
Is your problem solved ?

**Comment by andymachs** [comment]
> Is your problem solved ?

Yes, Thank you!!!

**Comment by amir1376** [comment]
OK so I close this then.
