### ISSUE TITLE
QOL: Always delete unfinished downloads from disk

### ISSUE THREAD

**Issue by CatPieLeaf** [amir1376/ab-download-manager#245]
When an unfinished download is paused, and the user attempts to delete it, the manager asks if they want to remove the files from the disk, or just delete the entry from the downloads list. This option should only be available for finished downloads.

I suggest to always delete the files from the disk if its an unfinished download. There is not much reasons for the user to keep files of unfinished downloads.

**Comment by amir1376** [comment]
I agreed. thanks
