### ISSUE TITLE
The height of the element is not centered.

### ISSUE THREAD

**Issue by in-ferno** [amir1376/ab-download-manager#254]
Russian language.
Справка > О программе > `Закрыть`

![pic](https://github.com/user-attachments/assets/7108bd80-a8e8-4b6c-905a-36acc3a77aa3)

**Comment by Himadrimani** [comment]
I can see that this issue has already been fixed. 

![Screenshot (293)](https://github.com/user-attachments/assets/b8c9e585-2585-4fae-b312-1bf935bbea1b)

**Comment by amir1376** [comment]
Thank you. I improved the "About" page
