### ISSUE TITLE
Fail to set default download dictionary

### ISSUE THREAD

**Issue by ji233-Sun** [amir1376/ab-download-manager#262]
Although I set the default download dictionary, the file always download to C as default.

**Comment by ji233-Sun** [comment]
![image](https://github.com/user-attachments/assets/f79992ed-cb70-41f6-bdd8-0dddb58754e0)

**Comment by Sunrongguo2008** [comment]
把使用分类去掉 #293

**Comment by amir1376** [comment]
its now fixed.
