### ISSUE TITLE
UI Scale option issues

### ISSUE THREAD

**Issue by andymachs** [amir1376/ab-download-manager#263]
UI Scale maximum is 2.0x, I found the value is still small. because the size of fonts look like small when set to 2.0x.
![image](https://github.com/user-attachments/assets/891a9450-50f5-4cc2-bb63-2767766c16de)

**Comment by amir1376** [comment]
Hi there. 2x is a huge scale. I'm curious what is your monitor configuration which you faced this problem.

- Can you please share a screenshot which compares this app with another application font scaling?
- What is your suggestion for maximum scale?

**Comment by andymachs** [comment]
> Hi there. 2x is a huge scale. I'm curious what is your monitor configuration which you faced this problem.
> 
> * Can you please share a screenshot which compares this app with another application font scaling?
> * What is your suggestion for maximum scale?

Please see the screenshot:  1.0x and 2.0x
My computer:
Display resolution：3000x2000
Scale: 225%

![image](https://github.com/user-attachments/assets/331b237b-6822-4182-ba49-7307c3a12278)

![image](https://github.com/user-attachments/assets/310c0048-b15b-4cce-9239-1b5ca3eeb885)

The visual effect is not good, So I think ABDM scale setting should be adjusted.

**Comment by amir1376** [comment]
Can you please share a **single** screenshot which contains this app (in 2x) and another app (like system settings but with your current system scale), So I can visually compare those.

**Comment by andymachs** [comment]
> Can you please share a **single** screenshot which contains this app (in 2x) and another app (like system settings but with your current system scale), So I can visually compare those.

Sorry, I do not use another app, Just use ABDM, Please refer to the screenshot above，These screenshot are based on my current system scale (225%). and display resolution：3000x2000.
