### ISSUE TITLE
Please support high resolution screen，e.g. 3K, 4K....

### ISSUE THREAD

**Issue by andymachs** [amir1376/ab-download-manager#264]
Some texts of UI and install UI are not clear and looks fuzzy.
Please support high resolution screen，e.g. 3K, 4K....

![image](https://github.com/user-attachments/assets/a68bac05-c7d4-4335-ae60-8a519d53faaa)

**Comment by amir1376** [comment]
Hi there. this is the behavior of NSIS installer and it is nothing that I can customize(like all of the other applications!)
