### ISSUE TITLE
The windows of download detail is too high.

### ISSUE THREAD

**Issue by andymachs** [amir1376/ab-download-manager#266]
The windows of download detail is too high. I think the windows should expand aspect ratio and make width become long.

![image](https://github.com/user-attachments/assets/cf211314-88be-4f82-aa14-bc592282f371)

**Comment by amir1376** [comment]
Well this is a detail of a download page and should give users a brief description about a download! it's acceptable that this page has lots of elements. but you can close the part info section (which is optional) if it takes too much space in your monitor.
