### ISSUE TITLE
[Feature] Proxy support

### ISSUE THREAD

**Issue by HEx-404** [amir1376/ab-download-manager#27]
Please add proxy support

**Comment by Ruikoto** [comment]
It's very necessary

**Comment by meiMingle** [comment]
It would be best if you could configure a proxy for each download task separately.

**Comment by amir1376** [comment]
@meiMingle 
> It would be best if you could configure a proxy for each download task separately.

good idea. I will consider this when I implemented a better download item settings so user can change or remove that proxy later
