### ISSUE TITLE
Is it possible to add the function of direct download? I don't want to confirm the direct download when downloading

### ISSUE THREAD

**Issue by Tgkkez** [amir1376/ab-download-manager#284]
I want to add the ability to block websites, some websites don't support downloading files using multi-threaded download tools

**Comment by andymachs** [comment]
I think current mode is very good~~

**Comment by amir1376** [comment]
Hi there, Thank you for your suggestion. However, the title does not accurately reflect the description, which has made it difficult for me to properly address the issues.

- If I understand you correctly the issue mentioned in the title is already covered by #89 .

- and the issue mentioned in the description is also covered by #241 . 

If I have misunderstood your issue, please reopen it with an updated title and description. so we can discuss about it further.
