### ISSUE TITLE
Why do I set the default path to F drive but it is automatically set to C drive every time I download?

### ISSUE THREAD

**Issue by huangyaohui5** [amir1376/ab-download-manager#293]
![01](https://github.com/user-attachments/assets/e4c6a742-576d-4b38-a688-58c7a9256fde)
![02](https://github.com/user-attachments/assets/67186d7e-a2f0-40ef-a97a-266c5953e98e)

Why do I set the default path to F drive but it is automatically set to C drive every time I download?

**Comment by youcai2016** [comment]
The default position of the categories has not changed.

**Comment by acercow** [comment]
me too

**Comment by amir1376** [comment]
its now fixed.
