### ISSUE TITLE
[Feature Request] Like IDM, start downloading the file before clicking the "Start Download" button

### ISSUE THREAD

**Issue by Sunrongguo2008** [amir1376/ab-download-manager#297]
From my observation, in IDM, before clicking the "Start Download" button, IDM has already started downloading files. This can save a few seconds of download time. I hope abdm can also provide similar functions.

**Comment by amir1376** [comment]
Hi there. unfortunately its not possible in this app. because this app does not use any temp directory and all downloaded data written directly to the final output file. because of that the output file should be selected by user before any download progress
