### ISSUE TITLE
Dispute around flags in front of Languages

### ISSUE THREAD

**Issue by YuZhouRen86** [amir1376/ab-download-manager#303]
The Beijing government (PRC government) is the only legal government in China according to UN, and the Taipei government ("RoC" government) 's "constitution" says it is the only legal government in China. However, we are all Chinese people. Both of the "constitution"s declare that there is only one China in the world. Simplified and traditional Chinese are two types of the Chinese characters, people around the world use them. To avoid controversy, I propose to remove the flag representing language, as most of the international companies do.

**Comment by amir1376** [comment]
Hi there. 
I add these flags just for decoration with no political intent. 
If they cause conflict or discomfort for dear users, then there is no need for them.

and thank you for mentioning that.
