### ISSUE TITLE
High memory usage on Linux

### ISSUE THREAD

**Issue by mfascioglu** [amir1376/ab-download-manager#309]
I don't know if this is normal? It takes up almost as much memory as a chromium-based program. Thanks.

Debian 12

![image](https://github.com/user-attachments/assets/417a7a85-03af-4ce6-9c3b-e0a8eadbae8b)

**Comment by salahoued** [comment]
I also noticed this in (openSUSE and Arch)
![2024-12-22-141540_hyprshot](https://github.com/user-attachments/assets/cfbc9b8c-a0a2-4986-82ef-0e116bb1b8dd)

@mfascioglu , I also used XDMan for a long while until I switched to Wayland (DEs/Compositors), but it also consumes a lot of memory (if you're using the 7 version Java based) you can confirm if you search for Java processes. If it's the new rewrite (version 8) you can ignore this comment.

**Comment by mfascioglu** [comment]
@salahoued I checked and compare it after read your answer. I am using lastest java [XDM ver. 7.2.11](https://xtremedownloadmanager.com/#downloads). Checking with various tools I could not detect any java process running in the background other than XDM. Therefore, I disagree with your comment. I don't know if this memory usage is normal. Maybe everything is as it should be.

![2024-12-22 21-23-09](https://github.com/user-attachments/assets/573702e4-71dd-4404-a84b-1cc1553f2e60)
![2024-12-22_20-50](https://github.com/user-attachments/assets/615d25e9-0a6f-4dec-a4a7-3823a5a4015e)

**Comment by salahoued** [comment]
Thank you for confirming. I see , maybe I was wrong, it's been a little while now that I used XDM.
Sorry about that

**Comment by amir1376** [comment]
Hello everyone. unfortunately this is a known bug. 
we talked about it [here](https://github.com/amir1376/ab-download-manager/issues/123#issuecomment-2425789466)
