### ISSUE TITLE
[Bug] autostart on Linux

### ISSUE THREAD

**Issue by YALdysse** [amir1376/ab-download-manager#310]
**Version:** `1.4.4`

### Description

The .desktop file used to autorun the application has a flaw. If the path to the application contains space characters, the application will not start because the path will be interpreted incorrectly.
For example, my path to app is: `/home/yaroslav/AB Donwload Manager/ABDownloadManager/bin/ABDownloadManager`

### Solution

The path to the application specified in the exec key must be escaped using the double quote character. For example:
`"/home/yaroslav/AB Donwload Manager/ABDownloadManager/bin/ABDownloadManager"`

Here is full code for `Exec` key:

> Exec="/home/yaroslav/AB Donwload Manager/ABDownloadManager/bin/ABDownloadManager" --background

**Comment by amir1376** [comment]
Thank you its fixed now.
