### ISSUE TITLE
Do you consider adapting to Chinese language in the future?

### ISSUE THREAD

**Issue by Hello-hao** [amir1376/ab-download-manager#44]
Are you considering adding multiple Chinese languages?

**Comment by amir1376** [comment]
@Hello-hao Hello, Yes sure. after setting up an i18n (internationalization) infrastructure for the app

What do you mean of `adding multiple Chinese language` ?

**Comment by zlf179** [comment]
> @Hello-hao Hello, Yes sure. after setting up an i18n (internationalization) infrastructure for the app
> 
> What do you mean of `adding multiple Chinese language` ?

i believe he is talking about simple Chinese and traditional Chinese

**Comment by GreenChennai** [comment]
Simplified Chinese,it's also schinese.

**Comment by redsonw** [comment]
Yes, what he said is that simplified Chinese is needed. I am also looking forward to supporting simplified Chinese.

**Comment by amir1376** [comment]
Chinese Added since `v1.4.0`
