### ISSUE TITLE
Multilanguage Support and Chinese Filename Parsing Issue

### ISSUE THREAD

**Issue by Atlantis-Gura** [amir1376/ab-download-manager#46]
First of all, thank you for creating such an excellent download manager. Your work is greatly appreciated!

## Multilanguage Support

Have you considered adding multilanguage support to the program? I would be happy to assist by providing translations for Simplified Chinese and German.

## Chinese Filename Parsing Issue

I've encountered a small issue when trying to download files with Chinese characters in the filename from a self-hosted Cloudreve instance. The Chinese characters are not being parsed correctly.

### Steps to Reproduce:
1. Set up a local Cloudreve instance
2. Try to download a file with Chinese characters in the filename
3. Observe the parsed filename in ab-download-manager

### Example:
- Original filename: "KomNetze_Prakt_V02_中文翻译.pdf"
- Download URL: `http://x.x.x.x:xxxx/api/v3/file/download/9cUxR4LNDVf8gdlG?sign=btph8rt20jqP3eWFuLQQYAUiMtF1qhrvLQ0MQMBUKsg%3D%3A1724436075`
- Parsed filename by ab-download-manager: "KomNetze_Prakt_V02_%E4%B8%AD%E6%96%87%E7%BF%BB%E8%AF%91"

As you can see, the Chinese characters are not decoded properly and remain URL-encoded.

### Additional Information:
This issue seems to be specific to certain URL formats. For example, when downloading from GitHub or a local AList instance, Chinese filenames are parsed correctly. These URLs typically look like:
`https://github.com/Ceelog/DictionaryByGPT4/raw/main/%E5%A8%81%E5%A8%81%E7%9A%84GPT%E5%8D%95%E8%AF%8D%E6%9C%AC(8000%E8%AF%8D).mdx`

In these cases, ab-download-manager successfully decodes the Chinese characters in the filename.

Could you please look into this issue and consider implementing a more robust filename parsing method that can handle various URL encoding formats?

Thank you for your time and consideration!

**Comment by amir1376** [comment]
@Atlantis-Gura Hi, Thanks for reporting this
actually this is not related to Chinese! any `UTF8` character may have this issue too! . this bug exists for some URLs that uses `URL Encoded` which I have to fix that in next version

BTW thank you for you interest to translate the app 
after I setup an i18n (internationalization) for the app, I will use your help❤️
