### ISSUE TITLE
The default installer have issues in Windows

### ISSUE THREAD

**Issue by amir1376** [amir1376/ab-download-manager#47]
There are some problems when we want to install the app
- if users want to update the app when app is already running the installer can't close the app gracefully and it breaks the installation process or even corrupt the installation directory ( user have to manually close the app in `system tray` in order to successfully update the app)

- another problem is that after each installation `APP_ID` will change! so installer can't detect previews installation location! 

I already created an [issue](https://youtrack.jetbrains.com/issue/CMP-5883/Compose-desktop-app-unable-to-stop-gracefully) in the compose issue tracker and waiting for their response

**Comment by sitiom** [comment]
> 4. find PID of the app in task manager and try to stop it gracefully using cmd
>```
>taskkill /PID <PID>
>```
>5. after that you will see that app still remains in task manager!

Killing the process via the process name works:

![image](https://github.com/user-attachments/assets/5c0f8d33-8b8c-40c8-b447-d779dc7f024c)

**Comment by amir1376** [comment]
That's right, but you use `/F` here! which tries to `force` stop the app (non graceful stop)

The default installer does not have this flag to stop the app by force

To reproduce this just install a previous version and when app is running try to install the latest version!
You will notice that the installer can't stop the app and ask you to restart the computer to finish the installation!

**Comment by amir1376** [comment]
Finally I created an `nsis installer` for the app. now we can have more control and customization in windows
