### ISSUE TITLE
UI is black/blank on Wayland KDE

### ISSUE THREAD

**Issue by videoman614** [amir1376/ab-download-manager#48]
UI doesn't display anything on Wayland, works perfectly with X11.
My guess is this is an incompatibility with xwayland.
Tested on v1.0.7

![Screenshot_20240824_150129](https://github.com/user-attachments/assets/303ec970-edcc-4fad-9506-cbc47be6a013)

Operating System: Arch Linux 
KDE Plasma Version: 6.1.4
KDE Frameworks Version: 6.5.0
Qt Version: 6.7.2
Kernel Version: 6.10.6-arch1-1 (64-bit)
Graphics Platform: Wayland
Processors: 12 × 12th Gen Intel® Core™ i5-12400F
Memory: 62.6 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 3060/PCIe/SSE2
Manufacturer: ASUS

**Comment by amir1376** [comment]
@videoman614 Hi there thank you for reporting this. 
is this related to [this](https://github.com/JetBrains/compose-multiplatform/issues/1631)?

**Comment by videoman614** [comment]
> @videoman614 Hi there thank you for reporting this. is this related to [this issue](https://github.com/JetBrains/compose-multiplatform/issues/1631)?

Not sure but doesn't sound like it because it does startup normally and when trying to download something the download window does appear and I can download, it's just black/blank and I have to guess the UI elements.

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

I have tried switch to xorg-xwayland-git to see if there has been any commits that _might_ fix this but so far no luck.

**Comment by amir1376** [comment]
@videoman614 
This is somehow related to graphic environment.


This app uses [compose-multiplatform](https://github.com/JetBrains/compose-multiplatform) for GUI. 
it uses `Open GL` by default for its `render api` in linux

but you can override it by `SKIKO_RENDER_API` environment variable

possible values for Linux are
- `OPENGL` (default)
- `SOFTWARE_COMPAT`
- `SOFTWARE_FAST`

for example 
```
SKIKO_RENDER_API=SOFTWARE_FAST
```

**Comment by videoman614** [comment]
Working perfectly now.

Might be an NVIDIA issue.
