### ISSUE TITLE
Support  docker  deploy ？

### ISSUE THREAD

**Issue by sikenali** [amir1376/ab-download-manager#50]

**Comment by amir1376** [comment]
@sikenali can you explain why? and a use case ?

**Comment by sikenali** [comment]
> @sikenali can you explain why? and a use case ?

Download resources on NAS device.

**Comment by amir1376** [comment]
@sikenali If I correctly understand the use case you mentioned, it is not related to this app (its GUI, and does not have CLI environment at the moment)
