### ISSUE TITLE
[Feature] Close dialog after download

### ISSUE THREAD

**Issue by kamuridesu** [amir1376/ab-download-manager#53]
It's a really nice app, only waiting for #9 to replace my usual download manager. 
But it would be nice for the download dialog box to close automatically after the download is completed.

**Comment by amir1376** [comment]
@kamuridesu Hi there. I'm glad to here that🙏
You can safely close the `Download Dialog` it doesn't interrupt/stop your download progress

This `Download Dialog` is here for
- show the download progress
- Change some configs related to that download item (speed limit,connection count etc.)
- or open the downloaded file/folder ( if its completed )
