### ISSUE TITLE
[Bug] Can't download from cloud.mail.ru

### ISSUE THREAD

**Issue by ZorinFoss** [amir1376/ab-download-manager#6]
Hi @amir1376 

[SampleLink](https://cloud.mail.ru/public/x8aF/ZNNKnftGX)

**Comment by amir1376** [comment]
@ZorinFoss Thanks for reporting this
Yeah, it seems the link you provided, uses javascript to initiate download links in the browser!

I will find a solution and update the [browser extension](https://github.com/amir1376/ab-download-manager-browser-integration)

**Comment by amir1376** [comment]
@ZorinFoss Its fixed and published (it may take a day for chrome store to update the extension, but for firefox is already available now)
Thanks again ❤️

**Comment by ZorinFoss** [comment]
Thank you ❤️

**Comment by Yunexiz** [comment]
> [SampleLink](https://cloud.mail.ru/public/x8aF/ZNNKnftGX)

@amir1376 the downloads on this page don't work.
