### ISSUE TITLE
Download error (Windows operating system)

### ISSUE THREAD

**Issue by AmirMohammadPX** [amir1376/ab-download-manager#93]
It does not recognize some links and writes the file size as unknown and gives an error, but I can download the file in the browser.

**Comment by tomdog2016** [comment]
![Snipaste_2024-10-04_21-54-57](https://github.com/user-attachments/assets/58bc768f-ee6a-4bf3-8efb-50ba309d3579)

**Comment by tomdog2016** [comment]
where to find  the error.log, pls.

**Comment by amir1376** [comment]
@AmirMohammadPX Hi there 
> It does not recognize some links

Please give extra information so I can reproduce the problem!
( which error shown in the app , a link that have this problem etc...)

**Comment by amir1376** [comment]
@tomdog2016 
When a download gets error, a toast notification shows up in the main window ( in the bottom right of the page )
for now this error does not logged anywhere.

**Comment by tomdog2016** [comment]
![图片](https://github.com/user-attachments/assets/1e851d5f-f9a6-4650-a6c3-a227eaa7eb8c)

**Comment by amir1376** [comment]
@tomdog2016 It seems the link you are using requires authentication (login). you can use browser integration in order to add require credentials to the app from your browser (if you can access that resource from browser)

**Comment by tomdog2016** [comment]
like this?
![图片](https://github.com/user-attachments/assets/c69cda6f-8a69-4bff-88d0-1f32ce843e52)

**Comment by amir1376** [comment]
@tomdog2016 yes

**Comment by tomdog2016** [comment]
It worked, thanks.
