### ISSUE TITLE
Restrict renaming file extensions

### ISSUE THREAD

**Issue by arijit4** [amir1376/ab-download-manager#96]
First of all, a BIG THUMBS UP to your work! Thanks a lot @amir1376 for your extremely good project.

Now, when I download a file, I can rename the file which is a common feature. But, which is not so common is that, I can rename the `file extension` which can lead to issues if the user mistakes and messes up. Hope you will look into this.

**Comment by amir1376** [comment]
@arijit4 Hi there. Thank you very much🙏

I believe it's important to give users the flexibility to rename files as they see fit, including the extension, it is similar to how other download managers operate.

**Comment by arijit4** [comment]
Can't it be a option to be set please?

**Comment by amir1376** [comment]
actually I don't understand why it should be happen.
most of the times, user even not changes the filename at all
on the other hand he/she should have control on the file name

BTW its better to show a warning to user that he changed the file extension (to allow him to restore the original file extension)
